### ISSUE TITLE
Consider how many temporary types should be supported

### ISSUE THREAD

**Issue by making** [making/yavi#200]
Bean Validation supports following types

* `java.util.Date`
* `java.util.Calendar`
* `java.time.Instant`
* `java.time.LocalDate`
* `java.time.LocalDateTime`
* `java.time.LocalTime`
* `java.time.MonthDay`
* `java.time.OffsetDateTime`
* `java.time.OffsetTime`
* `java.time.Year`
* `java.time.YearMonth`
* `java.time.ZonedDateTime`
* `java.time.chrono.HijrahDate`
* `java.time.chrono.JapaneseDate`
* `java.time.chrono.MinguoDate`
* `java.time.chrono.ThaiBuddhistDate`

at least, we should support

- [x] `java.time.Instant` (#197)
- [x] `java.time.LocalDate`
- [x]  `java.time.LocalDateTime`
- [x]  `java.time.LocalTime`  (#197)
- [x]  `java.time.OffsetDateTime` (#197)
- [x]  `java.time.ZonedDateTime`

addition after 0.10.0

- [x] `java.time.Year` (#220)
- [x] `java.time.YearMonth` (#220)

Other than that?

**Comment by DiegoKrupitza** [comment]
I think in later stages `java.sql.Timestamp` could be useful. Although I think we should first focus on the ones that are listed under "at least, we should support", and later if it gets more traction slowly expand. 
Personally I think it is way more important to provide out of the box validation methods than 10+ different classes but only with rudimentary validation methods.
